CREATE TABLE IF NOT EXISTS CLIENT(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL varchar(50) UNIQUE
);
CREATE TABLE IF NOT EXISTS SENTIMENT(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEXTE varchar(50),
    TYPE varchar(10),
    CLIENT_ID INTEGER,
	FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID)
);
ALTER TABLE CLIENT
ADD COLUMN IF NOT EXISTS TELEPHONE varchar(15);